python compilation failed!

###output:


###error:
Traceback (most recent call last):
  File "/Users/zhaozhaozhaozhao/Unambigious_prompt/exp/output_tb_gen_tb_20250319/109/pychecker_4.py", line 83, in <module>
    outputs = check_output(stimulus_list)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaozhaozhaozhao/Unambigious_prompt/exp/output_tb_gen_tb_20250319/109/pychecker_4.py", line 66, in check_output
    tb_outputs.append(dut.load(stimulus))
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/zhaozhaozhaozhao/Unambigious_prompt/exp/output_tb_gen_tb_20250319/109/pychecker_4.py", line 44, in load
    out_any_bv = BinaryValue(value=out_any, n_bits=100)[1:100]
                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^
  File "/opt/anaconda3/envs/mage/lib/python3.11/site-packages/cocotb/binary.py", line 751, in __getitem__
    raise IndexError("High index greater than number of bits.")
IndexError: High index greater than number of bits.
