python compilation failed!

###output:


###error:
Traceback (most recent call last):
  File "/Users/zhaozhaozhaozhao/Unambigious_prompt/exp/output_tb_gen_tb_20250319/154/pychecker_4.py", line 115, in <module>
    outputs = check_output(stimulus_list)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaozhaozhaozhao/Unambigious_prompt/exp/output_tb_gen_tb_20250319/154/pychecker_4.py", line 98, in check_output
    tb_outputs.append(dut.load(stimulus))
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/zhaozhaozhaozhao/Unambigious_prompt/exp/output_tb_gen_tb_20250319/154/pychecker_4.py", line 69, in load
    self.mm = (mm_high << 4) | mm_low
               ^^^^^^^
UnboundLocalError: cannot access local variable 'mm_high' where it is not associated with a value
