python compilation failed!

###output:


###error:
Traceback (most recent call last):
  File "/Users/zhaozhaozhaozhao/Unambigious_prompt/exp/output_tb_gen_tb_20250319/111/pychecker_4.py", line 67, in <module>
    outputs = check_output(stimulus_list)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/zhaozhaozhaozhao/Unambigious_prompt/exp/output_tb_gen_tb_20250319/111/pychecker_4.py", line 50, in check_output
    tb_outputs.append(dut.load(stimulus))
                      ^^^^^^^^^^^^^^^^^^
  File "/Users/zhaozhaozhaozhao/Unambigious_prompt/exp/output_tb_gen_tb_20250319/111/pychecker_4.py", line 31, in load
    out_slice = in_bv[start_idx:end_idx]
                ~~~~~^^^^^^^^^^^^^^^^^^^
  File "/opt/anaconda3/envs/mage/lib/python3.11/site-packages/cocotb/binary.py", line 751, in __getitem__
    raise IndexError("High index greater than number of bits.")
IndexError: High index greater than number of bits.
